### ISSUE TITLE
博主 本机链接本机不行吗

### ISSUE THREAD

**Issue by gitzouyujie** [sxy407249209/SignalRWebRtcDemo#1]
![image](https://user-images.githubusercontent.com/53415028/175249023-5e763609-0b0c-41c7-a207-0bf23fa1fde9.png)

**Comment by sxy407249209** [comment]
用不同的浏览器打开，第一个浏览器 本地显示 远程不显示 。第二个浏览器 本地不显示 远程显示

**Comment by gitzouyujie** [comment]
OK 可以了 博主 有博客不 看到 github 就一条作品



在 2022-06-23 16:27:04，"kgxk" ***@***.***> 写道：

用不同的浏览器打开，第一个浏览器 本地显示 远程不显示 。第二个浏览器 本地不显示 远程显示
